general:
  state: True
  testnet: False
  tp: 0.005
  sl: 0.01
  compensation: 0.0001
  leverage: 10
  timeframe: 15
  position_size: 10 
  max_pos: 8 
  n_tickers: 80
  datapoints: 200 
  n_processes: 10 
  balance_limit: 2 
  symbol_llimit: 0.05
  symbol_hlimit: 100 
  n_future_candles: 20 
  strategy_function: martin_4
  api: bybit

api_keys:
  bybit:
    prod:
      api_key: "hidden"
      api_secret: "hidden"
    test:
      api_key: "hidden"
      api_secret: "hidden"
